import { test, expect } from "@playwright/test";
import { dentalFields } from "../../lib/intake-context";

test("desktop dental context and automatic simulation persist and serialize two tabs", async ({ page, context }) => {
  test.setTimeout(150000);
  await page.setViewportSize({ width: 1366, height: 768 });
  let token = "";
  page.on("request", (req) => { if (req.url().includes("/api/profile")) token = req.headers().authorization || token; });
  await page.goto("/login");
  await page.getByRole("button", { name: "Chưa có tài khoản? Đăng ký nhanh" }).click();
  await page.getByLabel("Họ và tên").fill("Bệnh nhân nha khoa demo");
  await page.getByLabel("Bệnh nhân", { exact: true }).check();
  await page.getByLabel("Email", { exact: true }).fill(`dental-${crypto.randomUUID()}@careflow.test`);
  await page.getByLabel("Mật khẩu", { exact: true }).fill("careflow-demo-123");
  await page.getByRole("button", { name: "Đăng ký", exact: true }).click();
  await expect(page).toHaveURL(/patient\/dashboard/);
  await page.getByRole("button", { name: "Bắt đầu khám nha khoa", exact: true }).click();
  await expect(page).toHaveURL(/patient\/appointments\//);
  await page.getByRole("button", { name: "Ẩn thanh bên", exact: true }).click();
  await expect(page.locator("#patient-sidebar")).toBeHidden();
  await page.getByText("Biểu mẫu lời khai · khi AI chưa sẵn sàng", { exact: true }).click();
  const values: Record<string, string> = {
    need: "Khám mới vì đau răng", location: "răng hàm dưới bên phải", onset: "ba ngày", severity: "6/10", pattern: "từng lúc", triggers: "nhai và uống lạnh", impact: "khó ngủ", course: "không đổi", history: "chưa xử lý răng này", medications: "chưa dùng thuốc", allergies: "không có dị ứng nào đã biết", conditions: "không có bệnh nền nào đã biết", age: "28", fever: "không sốt", bleeding: "không chảy máu", mouthOpening: "há miệng bình thường",
  };
  for (const [key, value] of Object.entries(values)) await page.getByLabel(dentalFields[key as keyof typeof dentalFields], { exact: true }).fill(value);
  await page.getByLabel("Hô hấp", { exact: true }).selectOption("Thở bình thường");
  await page.getByLabel("Khả năng nuốt", { exact: true }).selectOption("Nuốt bình thường");
  await page.getByLabel("Sưng", { exact: true }).selectOption("Không sưng");
  await page.getByRole("button", { name: "Lưu lời khai để xác nhận" }).click();
  await expect(page.getByRole("button", { name: "Xác nhận & lập hành trình" })).toBeEnabled();
  await page.getByRole("button", { name: "Xác nhận & lập hành trình" }).click();
  await expect(page.getByText("Bảng mô phỏng", { exact: false })).toHaveCount(0);
  await expect(page.getByText("Điều khiển demo", { exact: false })).toHaveCount(0);
  await expect(page.getByLabel("Tốc độ demo", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("region", { name: "Đề xuất đổi lộ trình" })).toBeVisible({ timeout: 45000 });
  await page.screenshot({ path: "test-results/dental-1366-proposal.png" });
  const endpoint = new URL(page.url()).pathname.replace("/patient/", "/api/");
  const read = async () => (await (await page.request.get(endpoint, { headers: { Authorization: token } })).json()).data;
  const paused = await read();
  expect(paused.simulationRun.status).toBe("PAUSED");
  expect(paused.intakeContext.facts.location.value).toBe(values.location);
  await page.waitForTimeout(2000);
  expect((await read()).revision).toBe(paused.revision);
  const other = await context.newPage();
  await other.goto(page.url());
  await expect(other.getByRole("region", { name: "Đề xuất đổi lộ trình" })).toBeVisible();
  await page.getByRole("button", { name: "Đồng ý đổi", exact: true }).click();
  await expect(page.getByRole("region", { name: "Đề xuất đổi lộ trình" })).toHaveCount(0);
  await page.reload();
  await page.setViewportSize({ width: 1920, height: 1080 });
  const flowSteps = page.getByRole("button", { name: "Xem chi tiết bước" });
  const stepCount = await flowSteps.count();
  expect(stepCount).toBeGreaterThan(0);
  await flowSteps.first().click();
  await expect(page.getByRole("region", { name: "Chi tiết bước" })).toBeVisible();
  await page.screenshot({ path: "test-results/dental-1920-detail.png" });
  await expect(page.getByRole("heading", { name: "Hành trình đã hoàn tất" })).toBeVisible({ timeout: 90000 });
  const done = await read();
  expect(done.steps.imaging.status).toBe("COMPLETED");
  expect(done.steps.medication.status).toBe("SKIPPED");
  expect(done.simulationRun.status).toBe("COMPLETED");
  await expect(flowSteps).toHaveCount(stepCount);
  await page.reload();
  await expect(page.getByRole("heading", { name: "Hành trình đã hoàn tất" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Xem chi tiết bước" })).toHaveCount(stepCount);
});
